sudo: required
services: 
    - docker

before_install:
    - docker build -t newpuppet2/multi-docker -f ./client/Dockerfile.dev ./client

script: 
   
    - docker run newpuppet2/multi-docker npm test -- --coverage

after_success:
    - docker build -t newpuppet2/multi-client ./client
    - docker build -t newpuppet2/multi-nginx ./nginx
    - docker build -t newpuppet2/multi-server ./server
    - docker build -t newpuppet2/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push newpuppet2/multi-client
    - docker push newpuppet2/multi-nginx
    - docker push newpuppet2/multi-server
    - docker push newpuppet2/multi-worker



